"""empty message

Revision ID: ccdd8b9a444e
Revises: 5adff71249bc
Create Date: 2025-11-08 11:46:58.663580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccdd8b9a444e'
down_revision = '5adff71249bc'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    if conn.dialect.has_table(conn, 'comment'):
        op.drop_table('comment')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('dataset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('comment_parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('comment_ibfk_1')),
    sa.ForeignKeyConstraint(['comment_parent_id'], ['comment.id'], name=op.f('comment_ibfk_2')),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], name=op.f('comment_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
